### ISSUE TITLE
Finish db proecting 

### ISSUE THREAD

**Issue by Hahhhayam** [No-Solo/no-solo-api#2]
https://lucid.app/lucidchart/c91f3de7-23f3-47f9-b4e1-1d324a43badd/edit?invitationId=inv_cb2bc9d4-46cc-4f31-94e1-e95ea320fb74&page=0_0#

**Comment by Sqvlen** [comment]
![NoSoloAPI - public](https://github.com/No-Solo/no-solo-api/assets/65315887/996ab74d-ff9d-4fd9-ad27-383016f38bdc)
![image](https://github.com/No-Solo/no-solo-api/assets/65315887/c8c72dad-5ce7-4aa5-ae50-0cd7b4399700)
